version: '3.8'

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx 
    hostname: nginx
    ports:
      - "80:80" 
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cloudflare-public-key.pem:/etc/nginx/ssl/nginx-cloudflare.crt:ro
      - ./cloudflare-private-key.pem:/etc/nginx/ssl/nginx-cloudflare.key:ro
    depends_on:
      - astro-notee
    networks:
      - main
    healthcheck:
      test: curl localhost || exit 1
      timeout: 10s
      interval: 30s
      retries: 5
    # environment:
    #   - FK=${PAUL}

  astro-notee: 
    image: registry.gitlab.com/thailephan-opensource/pet-note-astro-react:latest
    container_name: astro-notee
    hostname: astro-notee
    healthcheck:
      test: curl localhost || exit 1
      timeout: 10s
      interval: 30s
      retries: 5
    ports:
      - "3000:80" 
    networks:
      - main

networks:
  main:
    driver: bridge